name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm ci

      - name: Lint with ESLint
        run: |
          npm run lint

      - name: Run unit tests with Jest
        run: npm test -- --coverage